// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feeds_follow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFollow = `-- name: CreateFollow :one
INSERT INTO feed_follow (id, user_id, feed_id) 
VALUES ($1, $2, $3) 
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFollowParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, createFollow, arg.ID, arg.UserID, arg.FeedID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const getFollows = `-- name: GetFollows :many
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follow WHERE user_id = $1
`

func (q *Queries) GetFollows(ctx context.Context, userID uuid.UUID) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFollows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowsByFeedID = `-- name: GetFollowsByFeedID :one
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follow WHERE feed_id = $1 AND user_id = $2
`

type GetFollowsByFeedIDParams struct {
	FeedID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetFollowsByFeedID(ctx context.Context, arg GetFollowsByFeedIDParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, getFollowsByFeedID, arg.FeedID, arg.UserID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM feed_follow WHERE user_id = $1 AND feed_id = $2
`

type UnfollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.UserID, arg.FeedID)
	return err
}
