info:
  contact: {}
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Returns a simple hello message
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Get a hello message
      tags:
      - example
swagger: "2.0"
